config/routes.rb
MyBearEssentials::Application.routes.draw do
  root :to => 'dashboard#index'
  get "dashboard/index", :as => 'dashboard_index'

  get "dashboard/plan", :as => 'dashboard_plan'

  get "dashboard/check", :as => 'dashboard_check'

  resources :required_courses

  resources :specific_requirements

  resources :degrees

  resources :requirements

  resources :departments

  resources :courses

  resources :planners

  resources :records

  resources :semesters

  resources :users
  
  match "/login" => redirect("/auth/facebook"), :as => "login"
  match "/logout" => "session#destroy", :as => "logout"
  match "/auth/facebook/callback" => "session#create"

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  has_many :records
  has_many :planners
  has_many :required_courses
  
  def display_name
    self.department.acronym + self.number.to_s + ' ' + self.title
  end
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :specific_requirements
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/required_course.rb
class RequiredCourse < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  has_many :required_courses
  has_many :specific_requirements
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :records
  has_many :planners
end

app/models/specific_requirement.rb
class SpecificRequirement < ActiveRecord::Base
  belongs_to :requirement
  belongs_to :degree
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :records
  has_many :planners
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
    @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  def create
    @course = Course.new(params[:course])

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /courses/1
  def update
    @course = Course.find(params[:id])
 
    if @course.update_attributes(params[:course])
      redirect_to @course, notice: 'Course was successfully updated.' 
    else
      render action: "edit"     
    end
  end

  # DELETE /courses/1
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_url
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  def index
    @records = Record.all
  end

  # GET /records/1
  def show
    @record = Record.find(params[:id])
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  def create
    @record = Record.new(params[:record])
    if @record.save
      redirect_to @record, notice: 'Record was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /records/1
  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(params[:record])
      redirect_to @record, notice: 'Record was successfully updated.' 
    else
      render action: "edit"
    end
  end

  # DELETE /records/1
  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_url 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render action: "edit"
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :semester_id %><br />
    <%= f.number_field :semester_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.number_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <tr>
    <th>User</th>
    <th>Semester</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.user_id %></td>
    <td><%= record.semester_id %></td>
    <td><%= record.course_id %></td>
    <td><%= link_to 'Show', record %></td>
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= link_to 'Destroy', record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @record.user_id %>
</p>

<p>
  <b>Semester:</b>
  <%= @record.semester_id %>
</p>

<p>
  <b>Course:</b>
  <%= @record.course_id %>
</p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>