config/routes.rb
MyBearEssentials::Application.routes.draw do
  root :to => 'dashboard#index'
  get "dashboard/index", :as => 'dashboard_index'

  get "dashboard/plan", :as => 'dashboard_plan'

  get "dashboard/check", :as => 'dashboard_check'

  resources :required_courses

  resources :specific_requirements

  resources :degrees

  resources :requirements

  resources :departments

  resources :courses

  resources :planners

  resources :records

  resources :semesters

  resources :users
  
  match "/login" => redirect("/auth/facebook"), :as => "login"
  match "/logout" => "session#destroy", :as => "logout"
  match "/auth/facebook/callback" => "session#create"

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  has_many :records
  has_many :planners
  has_many :required_courses
  
  def display_name
    self.department.acronym + self.number.to_s + ' ' + self.title
  end
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :specific_requirements
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/required_course.rb
class RequiredCourse < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  has_many :required_courses
  has_many :specific_requirements
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :records
  has_many :planners
end

app/models/specific_requirement.rb
class SpecificRequirement < ActiveRecord::Base
  belongs_to :requirement
  belongs_to :degree
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :records
  has_many :planners
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
    @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  def create
    @course = Course.new(params[:course])

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /courses/1
  def update
    @course = Course.find(params[:id])
 
    if @course.update_attributes(params[:course])
      redirect_to @course, notice: 'Course was successfully updated.' 
    else
      render action: "edit"     
    end
  end

  # DELETE /courses/1
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_url
  end
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  # GET /degrees
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  def show
    @degree = Degree.find(params[:id])
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
    @degree = Degree.find(params[:id])
  end

  # POST /degrees
  def create
    @degree = Degree.new(params[:degree])   
    if @degree.save
      redirect_to @degree, notice: 'Degree was successfully created.' 
    else
      render action: "new" 
    end
  end

  # PUT /degrees/1
  def update
    @degree = Degree.find(params[:id])
    if @degree.update_attributes(params[:degree])
      redirect_to @degree, notice: 'Degree was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  # DELETE /degrees/1
  def destroy
    @degree = Degree.find(params[:id])
    @degree.destroy
    redirect_to degrees_url 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render action: "edit"
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/degrees/_form.html.erb
<%= form_for(@degree) do |f| %>
  <% if @degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% @degree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.number_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing degree</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<h1>Listing degrees</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Units</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @degrees.each do |degree| %>
  <tr>
    <td><%= degree.name %></td>
    <td><%= degree.units %></td>
    <td><%= link_to 'Show', degree %></td>
    <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
    <td><%= link_to 'Destroy', degree, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New degree</h1>

<%= render 'form' %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @degree.name %>
</p>

<p>
  <b>Units:</b>
  <%= @degree.units %>
</p>


<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Username</th>
    <th>Password</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.type %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Type:</b>
  <%= @user.type %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>