config/routes.rb
MyBearEssentials::Application.routes.draw do
  root :to => 'dashboard#index'
  get "dashboard/index", :as => 'dashboard_index'

  get "dashboard/plan", :as => 'dashboard_plan'

  get "dashboard/check", :as => 'dashboard_check'

  resources :required_courses

  resources :specific_requirements

  resources :degrees

  resources :requirements

  resources :departments

  resources :courses

  resources :planners

  resources :records

  resources :semesters

  resources :users
  
  match "/login" => redirect("/auth/facebook"), :as => "login"
  match "/logout" => "session#destroy", :as => "logout"
  match "/auth/facebook/callback" => "session#create"

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  has_many :records
  has_many :planners
  has_many :required_courses
  
  def display_name
    self.department.acronym + self.number.to_s + ' ' + self.title
  end
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :specific_requirements
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
  belongs_to :course
end

app/models/required_course.rb
class RequiredCourse < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  has_many :required_courses
  has_many :specific_requirements
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :records
  has_many :planners
end

app/models/specific_requirement.rb
class SpecificRequirement < ActiveRecord::Base
  belongs_to :requirement
  belongs_to :degree
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :records
  has_many :planners
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/specific_requirements_controller.rb
class SpecificRequirementsController < ApplicationController
  # GET /specific_requirements
  # GET /specific_requirements.json
  def index
    @specific_requirements = SpecificRequirement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specific_requirements }
    end
  end

  # GET /specific_requirements/1
  # GET /specific_requirements/1.json
  def show
    @specific_requirement = SpecificRequirement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specific_requirement }
    end
  end

  # GET /specific_requirements/new
  # GET /specific_requirements/new.json
  def new
    @specific_requirement = SpecificRequirement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specific_requirement }
    end
  end

  # GET /specific_requirements/1/edit
  def edit
    @specific_requirement = SpecificRequirement.find(params[:id])
  end

  # POST /specific_requirements
  # POST /specific_requirements.json
  def create
    @specific_requirement = SpecificRequirement.new(params[:specific_requirement])

    respond_to do |format|
      if @specific_requirement.save
        format.html { redirect_to @specific_requirement, notice: 'Specific requirement was successfully created.' }
        format.json { render json: @specific_requirement, status: :created, location: @specific_requirement }
      else
        format.html { render action: "new" }
        format.json { render json: @specific_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specific_requirements/1
  # PUT /specific_requirements/1.json
  def update
    @specific_requirement = SpecificRequirement.find(params[:id])

    respond_to do |format|
      if @specific_requirement.update_attributes(params[:specific_requirement])
        format.html { redirect_to @specific_requirement, notice: 'Specific requirement was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @specific_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specific_requirements/1
  # DELETE /specific_requirements/1.json
  def destroy
    @specific_requirement = SpecificRequirement.find(params[:id])
    @specific_requirement.destroy

    respond_to do |format|
      format.html { redirect_to specific_requirements_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render action: "edit"
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/specific_requirements_helper.rb
module SpecificRequirementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/specific_requirements/_form.html.erb
<%= form_for(@specific_requirement) do |f| %>
  <% if @specific_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specific_requirement.errors.count, "error") %> prohibited this specific_requirement from being saved:</h2>

      <ul>
      <% @specific_requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degree_id %><br />
    <%= f.number_field :degree_id %>
  </div>
  <div class="field">
    <%= f.label :requirement_id %><br />
    <%= f.number_field :requirement_id %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.number_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specific_requirements/edit.html.erb
<h1>Editing specific_requirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @specific_requirement %> |
<%= link_to 'Back', specific_requirements_path %>

app/views/specific_requirements/index.html.erb
<h1>Listing specific_requirements</h1>

<table>
  <tr>
    <th>Degree</th>
    <th>Requirement</th>
    <th>Units</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specific_requirements.each do |specific_requirement| %>
  <tr>
    <td><%= specific_requirement.degree_id %></td>
    <td><%= specific_requirement.requirement_id %></td>
    <td><%= specific_requirement.units %></td>
    <td><%= link_to 'Show', specific_requirement %></td>
    <td><%= link_to 'Edit', edit_specific_requirement_path(specific_requirement) %></td>
    <td><%= link_to 'Destroy', specific_requirement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specific requirement', new_specific_requirement_path %>

app/views/specific_requirements/new.html.erb
<h1>New specific_requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', specific_requirements_path %>

app/views/specific_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Degree:</b>
  <%= @specific_requirement.degree_id %>
</p>

<p>
  <b>Requirement:</b>
  <%= @specific_requirement.requirement_id %>
</p>

<p>
  <b>Units:</b>
  <%= @specific_requirement.units %>
</p>


<%= link_to 'Edit', edit_specific_requirement_path(@specific_requirement) %> |
<%= link_to 'Back', specific_requirements_path %>